In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as pp

In [2]:
data = pd.read_csv("Normalized_data.csv")

In [3]:
data.head()

Mean radius  Mean texture  Mean perimeter  Mean area  Mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   Mean compactness  Mean concavity  Mean concave points  Mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   Mean fractal dimension  ...  Worst or Largest texture  \
0                2.255747  ...                 -1.359293   
1               -0.868652  ...                 -0.369203   
2               -0.398008  ...                 -0.023974   
3                4.910919  ...                  0.133984   
4               -0.562450  ...                 -1.466770   

   Worst or Largest perimeter  Worst or Largest area  \
0                    2.303601               2.001237   
1                    1.535126               1.890489   
2                    1.347475               1.456285   
3                   -0.249939              -0.550021   
4                    1.338539               1.220724   

   Worst or Largest smoothness  Worst or Largest compactness  \
0                     1.307686                      2.616665   
1                    -0.375612                     -0.430444   
2                     0.527407                      1.082932   
3                     3.394275                      3.893397   
4                     0.220556                     -0.313395   

   Worst or Largest concavity  Worst or Largest concave points  \
0                    2.109526                         2.296076   
1                   -0.146749                         1.087084   
2                    0.854974                         1.955000   
3                    1.989588                         2.175786   
4                    0.613179                         0.729259   

   Worst or Largest symmetry  Worst or Largest fractal dimension  Labels  
0                   2.750622                            1.937015       M  
1                  -0.243890                            0.281190       M  
2                   1.152255                            0.201391       M  
3                   6.046041                            4.935010       M  
4                  -0.868353                           -0.397100       M  

[5 rows x 31 columns]

In [4]:
x = data.iloc[:, 0:30].values
y = data.iloc[:, 30].values

In [5]:
data_m = data.query('Labels == "M"')

In [6]:
data_b = data.query('Labels == "B"')

In [7]:
x_m = data_m.iloc[: , 0:30]
y_m = data_m.iloc[: , 30]
y_b = data_b.iloc[: , 30]
x_b = data_b.iloc[: , 0:30]

In [8]:
x_m.to_numpy()
y_m.to_numpy()
y_b.to_numpy()
x_b.to_numpy()

array([[-0.16679919, -1.1471623 , -0.18572799, ...,  0.21612292,
         0.12334653, -0.62929189],
       [-0.29744572, -0.83300824, -0.26110606, ..., -0.63610973,
         0.45822712, -0.11724974],
       [-1.31308049, -1.59395919, -1.30280622, ..., -0.7969026 ,
        -0.72922385, -0.34445459],
       ...,
       [-0.02195195,  1.82915656, -0.0242624 , ..., -0.14931541,
        -1.05277997, -0.04077591],
       [-0.83139241,  2.34576546, -0.87731145, ..., -1.74506282,
        -2.15934191, -1.37962206],
       [-1.80840124,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

### Calculating the mean difference of two classes

In [9]:
mean = x_m.mean()-x_b.mean()

In [11]:
x_mt = np.transpose(x_m)

In [12]:
x_m.shape

(212, 30)

In [13]:
y_mt = np.transpose(x_m)

In [14]:
S_xmt = np.cov(x_mt)

In [15]:
S_ymt = np.cov(y_mt)

### Adding covariance of two classes

In [16]:
S = S_xmt+S_ymt

In [17]:
Si = np.linalg.inv(S)

In [18]:
W = np.matmul(Si, mean)

In [19]:
Si.shape

(30, 30)

In [20]:
mean.shape

(30,)

In [21]:
W

array([ -2.59959352,  -1.0213171 ,  18.79920443, -11.53201766,
         1.5757664 ,  -1.2983485 ,  -2.1008193 ,   0.09086002,
        -0.65790628,  -0.56484001,   1.5930724 ,  -0.55563768,
        -2.71681954,   3.001523  ,  -0.33599296,   1.37420918,
        -0.92090242,   1.93124282,  -0.43886882,  -1.72572394,
         2.28475672,   2.23477336,   1.96367995,  -5.89764971,
         0.24390599,  -1.61197724,   1.30709358,   0.46140744,
         0.85924592,   1.48385997])

In [22]:
W.shape

(30,)

In [23]:
New_Attribute = np.matmul(x,W)

In [24]:
New_Attribute.shape

(569,)

In [25]:
R = pd.DataFrame(New_Attribute)

In [26]:
R['labels'] = y

In [27]:
R

0 labels
0     5.540609      M
1     4.972206      M
2     9.882738      M
3     2.964373      M
4     4.514711      M
..         ...    ...
564   9.022339      M
565   8.651791      M
566   5.447909      M
567  10.089560      M
568 -20.901417      B

[569 rows x 2 columns]

In [28]:
print(R.describe())

                  0
count  5.690000e+02
mean  -1.476152e-10
std    6.370808e+00
min   -2.437254e+01
25%   -3.941461e+00
50%    2.053414e-01
75%    5.344387e+00
max    1.152286e+01


In [63]:
R.to_csv('Fisher result.csv', index = False)

In [73]:
data["Labels"] = np.where(data["Labels"].str.contains("M"), 1, 0)

In [74]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [75]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [83]:
clf = LinearDiscriminantAnalysis()
clf.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [84]:
pred = clf.predict(x_test)

In [85]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [86]:
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[106   2]
 [  6  57]]
              precision    recall  f1-score   support

           B       0.95      0.98      0.96       108
           M       0.97      0.90      0.93        63

    accuracy                           0.95       171
   macro avg       0.96      0.94      0.95       171
weighted avg       0.95      0.95      0.95       171

